apiVersion: v1
kind: ReplicationController
metadata:
  name: replication-controller-app
  labels:
    app: replication-controller-app
    tier: frontend
spec:
  template:
    metadata:
      name: nginx-pod
      labels:
        app: mynginx
        type: front-end
    spec:
      containers:
        - name: nginx-container
          image: nginx
replicas: 3
