- hosts: webservers
  gather_facts: true
  become_user: root

  vars_files:
    - ./vars.yml

  tasks:
  - name: Install Nginx
    dnf: pkg=nginx state=present
    notify:
    - restart nginx
  - name: Enable Nginx during boot
    service: name=nginx state=started enabled=yes
  handlers:
    - name: restart nginx
      service: name=nginx state=restarted

- hosts: dbservers
  become_user: yes
  tasks:
  - name: Install mysql
    dnf: pkg=mysql-server state=present