apiVersion: v1
kind: pod
metadata:
  name: angular-list
  labels:
    app: web
spec:
  containers:
    - name: angular-list
      image: mhellnerdev/angular-list
      ports:
        - containerPort: 5001
d