---
- name: Install Docker on Rocky 8
  hosts: all
  become: yes

  vars:
    docker_user: root

  tasks:
    - name: Update package cache
      command: sudo dnf check-update
      register: dnf_check_update_result
      failed_when: dnf_check_update_result.rc > 100

    - name: Add Docker repository
      command: sudo dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

    - name: Install Docker packages
      command: sudo dnf install docker-ce docker-ce-cli containerd.io -y

    - name: Start Docker service
      command: sudo systemctl start docker

    - name: Enable Docker service at boot
      command: sudo systemctl enable docker

    - name: Check Docker service status
      command: sudo systemctl status docker

    - name: Add user to Docker group
      user:
        name: '{{ docker_user }}'
        groups: docker
        append: yes
