- hosts: webservers
  gather_facts: yes
  become: yes
  
  tasks:
  
  - name: Ensure nginx service is stopped
    service:
      name: nginx
      state: stopped
    ignore_errors: yes
  
  - name: Remove Nginx
    apt: 
      name: nginx 
      state: absent
    notify:
    - removed nginx 
  
  - name: Remove and Stop Nginx during boot
    service: name=nginx state=stopped enabled=no
  
  - name: Clean unused packages
    apt:
      autoremove: yes
      purge: yes
  
  handlers:
    - name: removed nginx
      service: name=nginx state=stopped
  