# global config
global:
  scrape_interval:     5s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 5s # Evaluate rules every 15 seconds. The default is every 1 minute.

# A scrape configuration containing exactly one endpoint to scrape:
scrape_configs:
  - job_name: 'WMI'
    static_configs:
      - targets: ['172.16.29.147:9182'] # the address of an application that exposes metrics for prometheus
  
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']